### ISSUE TITLE
Fix topic-closing-info position

### ISSUE THREAD

**Issue by erengy** [hummingbird-me/hummingbird#18]
![topic-closing-info](https://cloud.githubusercontent.com/assets/1078430/3208788/d8b805c8-ee45-11e3-81aa-99d173629267.gif)

``` css
#topic-closing-info {
  padding: 15px 10px 5px 15px;
}
```

I'm not sure if the problem lies within Discourse or Hummingbird.
