### ISSUE TITLE
Fix Genres padding on activity updates

### ISSUE THREAD

**Issue by Wopian** [hummingbird-me/hummingbird#417]
The in-line list of genres on activity updates has a `padding-right` which makes it look awkward and makes genres use way more space than needed.

With padding:
![](http://a.pomf.se/mibwxl.png)

Without padding:
![](http://a.pomf.se/ujznmz.png)

Caused by a CSS override here:

```css
.inline-list li,
.update-panel .genre-list li {
    display: inline-block;
    float: left;
    padding-right: 10px; /* This line */
}

.update-panel .inline-list li,
.update-panel .genre-list li {
    padding-right: 0;
}
```
